sudo: required  
dist: trusty  

language: node_js 

node_js:
  - "6.3"
python:
  - "3.4"

env:
  global:  
    - CLI_VERSION=latest
    - COMMIT=${TRAVIS_COMMIT::8}
    - DOTNET_CLI_TELEMETRY_OPTOUT=1

services:
  - docker

before_install: 
  # NOTE: we could compile the application in a docker image instead
  - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
  - sudo apt-get update
  - sudo apt-get install dotnet-dev-1.0.0-preview2.1-003177

install:  
    - dotnet restore ./src/AcsTest.WebAPI/project.json

script: 
  #- dotnet test
  - echo "No tests"

after_success:
  - export REPO_API=richardcase/acstest-api
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - export VERSION=`cat ./VERSION`
  - export BUILDDATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
  - dotnet publish ./src/AcsTest.WebAPI/project.json -c release -o publish
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - cd publish
  - docker build -f  ../src/AcsTest.WebAPI/Dockerfile -t $REPO_API:$COMMIT --build-arg BUILD_DATE=$BUILDDATE --build-arg VCS_REF=$COMMIT --build-arg VERSION=$VERSION .
  - docker tag $REPO_API:$COMMIT $REPO_API:$TAG
  - docker tag $REPO_API:$COMMIT $REPO_API:travis-$TRAVIS_BUILD_NUMBER
  - docker tag $REPO_API:$COMMIT $REPO_API:$VERSION
  - docker push $REPO_API